### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Rin-Rem** [Evanaellio/HyperJump#4]
I have it installed, but it does not seem to be working. If anything while its installed my jumps feel shorter then normal.

**Comment by Evanaellio** [comment]
I guess you were using it with Boneworks ?
It was unfortunately not supported in v2 but I just released v3 https://github.com/Evanaellio/HyperJump/releases/tag/v3.0.0 with support for both Boneworks and Bonelab (patch 2).
